# .golangci.yml

run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 3m

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA1019:.*github.com/jhump/protoreflect.*deprecated'
