before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X {{ .ModulePath }}/cmd.Version={{.Tag}} -X {{ .ModulePath }}/cmd.GitCommit={{.ShortCommit}} -X {{ .ModulePath }}/cmd.BuildTime={{.Date}}
    goos:
      - darwin
      - linux
      - windows
#    hooks:
#      post: './generate_completion.sh {{ .Target }} {{ .Path }}'

archives:
  - id: default
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
nfpms:
  - id: default
    vendor: Device Insight GmbH
    homepage: https://www.device-insight.com/
    maintainer: Dirk Wilden <[dirk.wilden@device-insight.com]>
    description: A command-line interface for interaction with Apache Kafka
    license: Apache 2.0

    formats:
      - deb
      - rpm

release:
  disable: false
  draft: false

snapcrafts:
  - id: default
    publish: true
    summary: A command-line interface for interaction with Apache Kafka
    description: |
      A Commandline interface for Apache Kafka which provides useful features adapted from kubectl for Kubernetes.
      Multiple kafka brokers can be configured in a config file and the active broker is also persisted within the config.
      In addition kafkactl supports auto-completion for its commands as well as topic names.
    grade: stable
    confinement: strict
    license: Apache-2.0
    apps:
      kafkactl:
        plugs: ["home", "network", "dot-kube", "config-kafkactl"]
        completer: kafkactl-completion.bash
    plugs:
      dot-kube:
        interface: personal-files
        read:
          - $HOME/.kube
      config-kafkactl:
        interface: personal-files
        write:
          - $HOME/.config/kafkactl/config.yml
brews:
  -
    repository:
      owner: deviceinsight
      name: homebrew-packages

    commit_author:
      name: goreleaserbot
      email: goreleaser@device-insight.com

    folder: Formula

    homepage: https://www.device-insight.com/

    description: |
      A Commandline interface for Apache Kafka which provides useful features adapted from kubectl for Kubernetes.
      Multiple kafka brokers can be configured in a config file and the active broker is also persisted within the config.
      In addition kafkactl supports auto-completion for its commands as well as topic names.

    skip_upload: false

dockers:
  -
    skip_push: false
    dockerfile: Dockerfile.Ubuntu
    image_templates:
      - "deviceinsight/kafkactl:latest-ubuntu"
      - "deviceinsight/kafkactl:{{ .Tag }}-ubuntu"
      - "deviceinsight/kafkactl:latest"
      - "deviceinsight/kafkactl:{{ .Tag }}"
  -
    skip_push: false
    dockerfile: Dockerfile.Scratch
    image_templates:
      - "deviceinsight/kafkactl:latest-scratch"
      - "deviceinsight/kafkactl:{{ .Tag }}-scratch"

publishers:
  - name: aur-kafkactl
    env:
      - AUR_SSH_PRIVATE_KEY={{ .Env.AUR_SSH_PRIVATE_KEY }}
    cmd: |
      .github/aur/kafkactl/publish.sh {{ .Version }}