name: Build and Test

on:
  push:
    branches:
      - master
      - feature/tests
    tags: []
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
          
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run Unit tests
        run: make test

  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # cp-version 5.5.x corresponds to kafka version 2.5.x
        cp-version: [5.5.0, 5.4.2, 5.3.3]
    env:
      CP_VERSION: ${{ matrix.cp-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run integration tests
        run: make integration_test

  build:
    name: Build
    runs-on: ubuntu-latest 
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: make build
