name: Lint / Test / IT

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: 'go.mod'
      - name: Run Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: 'go.mod'
      - name: Run Unit tests
        run: make test
      - name: Upload logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: test-logs
          path: test.log

  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://docs.confluent.io/platform/current/installation/versions-interoperability.html
        kafka_version: [3.9.0, 3.8.0, 3.7.0]
        include:
          - kafka_version: 3.9.0
            cp_version: 7.9.2
          - kafka_version: 3.8.0
            cp_version: 7.8.3
          - kafka_version: 3.7.0
            cp_version: 7.7.4

    env:
      CP_VERSION: ${{ matrix.cp_version }}
      KAFKAVERSION: ${{ matrix.kafka_version }}
      REQUESTTIMEOUT: 15s
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: 'go.mod'
      - name: Run integration tests
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4
        with:
          max_attempts: 2
          retry_on: error
          timeout_minutes: 10
          command: make integration_test
      - name: Upload logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: it-logs-${{ matrix.cp_version }}
          path: integration-test.log
          overwrite: true
