name: Publish github pages
on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      -
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: 'go.mod'
      -
        name: Build and generate docs
        run: make docs DOCS_TARGET=pages
      -
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          folder: pages
